1. e4  Nf6 
2. e5  Ng8 
3. d4  d5 
4. Nf3  c6 
5. Bd3  e6 
6. 0-0  c5 
7. c3  Nc6 
8. Re1  cxd4 
9. cxd4  h6 
10. Nc3  Bd7 
11. a3  Nge7 
12. b4  a6 
13. Bd2  Rc8 
14. Rc1  Ng6 
15. Na4  Ra8 
16. Nc5  Bxc5 
17. Rxc5  Nh4 
18. Be3  b6 
19. Rc3  Nf5 
20. Bxf5  exf5 
21. e6  fxe6 
22. Rxc6  Bxc6 
23. Ne5  O-O 
24. Nxc6  Qc7 
25. Ne5  Rac8 
26. Bf4  g5 
27. Bd2  Kh7 
28. Qh5  Rg8 
29. h4  Qxe5 
30. Rxe5  Rce8 
31. hxg5  Rgf8 
32. Qxh6+  Kg8 
33. g6  Re7 
34. Rxe6  Rg7 
35. Bf4  Rc7 
36. Bxc7  Rf7 
37. Re8+  Rf8 
38. Rxf8# 
Game over. Total time: 574.4566328525543 seconds
Result: 1-0
. . . . . R k .
. . B . . . . .
p p . . . . P Q
. . . p . p . .
. P . P . . . .
P . . . . . . .
. . . . . P P .
. . . . . . K .

1. e4  e6 
2. d4  Nf6 
3. Nc3  d5 
4. e5  Ng8 
5. f4  a6 
6. Nf3  b6 
7. Be3  c5 
8. Qd2  c4 
9. g4  Ne7 
10. 0-0-0  Nbc6 
11. Bh3  b5 
12. f5  exf5 
13. gxf5  Bxf5 
14. Bxf5  g6 
15. Bh3  b4 
16. Ne2  c3 
17. bxc3  Na5 
18. Error parsing move Ke1: illegal san: 'Ke1' in r2qkb1r/4np1p/p5p1/n2pP3/1p1P4/2P1BN1B/P1PQN2P/2KR3R w kq - 1 18
Error parsing move Ke1: illegal san: 'Ke1' in r2qkb1r/4np1p/p5p1/n2pP3/1p1P4/2P1BN1B/P1PQN2P/2KR3R w kq - 1 18
Error parsing move Ke1: illegal san: 'Ke1' in r2qkb1r/4np1p/p5p1/n2pP3/1p1P4/2P1BN1B/P1PQN2P/2KR3R w kq - 1 18
cxb4  Nc4 
19. Qd3  Rb8 
20. c3  Qb6 
21. Error parsing move 0-0: illegal san: '0-0' in 1r2kb1r/4np1p/pq4p1/3pP3/1PnP4/2PQBN1B/P3N2P/2KR3R w k - 1 21
Error parsing move 0-0: illegal san: '0-0' in 1r2kb1r/4np1p/pq4p1/3pP3/1PnP4/2PQBN1B/P3N2P/2KR3R w k - 1 21
Error parsing move 0-0: illegal san: '0-0' in 1r2kb1r/4np1p/pq4p1/3pP3/1PnP4/2PQBN1B/P3N2P/2KR3R w k - 1 21
Error parsing move 0-0: illegal san: '0-0' in 1r2kb1r/4np1p/pq4p1/3pP3/1PnP4/2PQBN1B/P3N2P/2KR3R w k - 1 21
Nd2  Nxe3 
22. Qxe3  Qb5 
23. Nb3  a5 
24. Nxa5  Ng8 
25. Kc2  Qa4+ 
26. Kd3  Bh6 
27. Qf3  Ne7 
28. Error parsing move Ke2: illegal san: 'Ke2' in 1r2k2r/4np1p/6pb/N2pP3/qP1P4/2PK1Q1B/P3N2P/3R3R w k - 7 28
Error parsing move Ke2: illegal san: 'Ke2' in 1r2k2r/4np1p/6pb/N2pP3/qP1P4/2PK1Q1B/P3N2P/3R3R w k - 7 28
Rhf1  O-O 
29. Nc1  Rxb4 
30. Nab3  f5 
31. Ke2  Rbb8 
32. Ke1  Qa3 
33. Ke2  g5 
34. Ke1  Rb6 
35. Ke2  g4 
36. Ke1  gxf3 
37. Error parsing move Ke2: illegal san: 'Ke2' in 5rk1/4n2p/1r5b/3pPp2/3P4/qNP2p1B/P6P/2NRKR2 w - - 0 37
Error parsing move Ke2: illegal san: 'Ke2' in 5rk1/4n2p/1r5b/3pPp2/3P4/qNP2p1B/P6P/2NRKR2 w - - 0 37
Error parsing move Ke2: illegal san: 'Ke2' in 5rk1/4n2p/1r5b/3pPp2/3P4/qNP2p1B/P6P/2NRKR2 w - - 0 37
Error parsing move Ke2: illegal san: 'Ke2' in 5rk1/4n2p/1r5b/3pPp2/3P4/qNP2p1B/P6P/2NRKR2 w - - 0 37
Error parsing move Ke2: illegal san: 'Ke2' in 5rk1/4n2p/1r5b/3pPp2/3P4/qNP2p1B/P6P/2NRKR2 w - - 0 37
<__main__.GPTPlayer object at 0x7fd80fa09150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa09150>

Game over. Total time: 612.1773211956024 seconds
Result: *
. . . . . r k .
. . . . n . . p
. r . . . . . b
. . . p P p . .
. . . P . . . .
q N P . . p . B
P . . . . . . P
. . N R K R . .

1. e4  c6 
2. d4  Nf6 
3. Nc3  Qa5 
4. Bd3  d6 
5. Nf3  e5 
6. 0-0  Bg4 
7. dxe5  Bxf3 
8. Qxf3  dxe5 
9. Bd2  Nbd7 
10. Rad1  Bd6 
11. Nb5  Bb4 
12. Bxb4  Qxb4 
13. Nc7+  Ke7 
14. Nxa8  Rxa8 
15. b3  Kf8 
16. Rfe1  Qc3 
17. Qe3  Nc5 
18. Qd2  Qxd2 
19. Error while getting GPT response: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600)
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Rxd2  Rd8 
20. Red1  Rd6 
21. f3  Ke7 
22. Kf2  h5 
23. Ke3  g5 
24. Ke2  Ne6 
25. Ke1  g4 
26. Ke2  a5 
27. Ke3  h4 
28. Ke2  gxf3+ 
29. Ke3  fxg2 
30. Ke2  Ng5 
31. Ke3  Ng4+ 
32. Ke2  Rf6 
33. Ke1  g1=Q+ 
34. Ke2  Qe3# 
Game over. Total time: 25720.192977428436 seconds
Result: 0-1
. . . . . . . .
. p . . k p . .
. . p . . r . .
p . . . p . n .
. . . . P . n p
. P . B q . . .
P . P R K . . P
. . . R . . . .

1. e4  Nf6 
2. e5  Nd5 
3. d4  d6 
4. Nf3  g6 
5. Bc4  c6 
6. 0-0  Nb6 
7. Bb3  d5 
8. Re1  Bg4 
9. Nbd2  a5 
10. a4  e6 
11. h3  Bxf3 
12. Nxf3  c5 
13. c3  cxd4 
14. Nxd4  Bc5 
15. Bh6  Qh4 
16. Qd2  Bxd4 
17. cxd4  Qe7 
18. Rec1  Rg8 
19. Bg5  Qd7 
20. Rc5  Na6 
21. Rxa5  Rc8 
22. Rc1  Rxc1+ 
23. Qxc1  Qc8 
24. Qxc8+  Nxc8 
25. Bd1  Na7 
26. Be2  h6 
27. Bf6  Kd7 
28. Bxa6  bxa6 
29. Rxa6  Nc6 
30. b4  Nxb4 
31. Ra7+  Kc6 
32. Rxf7  Rb8 
33. Re7  Ra8 
34. Rxe6+  Kc7 
35. Re7+  Kc8 
36. Re8+  Kd7 
37. Rxa8  g5 
38. Rh8  h5 
39. Rxh5  g4 
40. hxg4  Kc8 
41. g5  Nc6 
42. g6  Na7 
43. g7  Kc7 
44. g8=Q  Nc8 
45. Qxd5  Kb6 
46. Qc5+  Kb7 
47. Rh7+  Ka6 
48. Qb5# 
Game over. Total time: 751.6999931335449 seconds
Result: 1-0
. . n . . . . .
. . . . . . . R
k . . . . B . .
. Q . . P . . .
P . . P . . . .
. . . . . . . .
. . . . . P P .
. . . . . . K .

1. e4  Nf6 
2. e5  Ne4 
3. Ke2  g6 
4. Ke3  d5 
5. Ke2  Bg4+ 
6. Ke1  Bxd1 
7. Kxd1  Qc8 
8. Ke1  Nxf2 
9. Ke2  Nxh1 
10. Ke1  Qf5 
11. Ke2  Qe4+ 
12. Kd1  Nf2# 
Game over. Total time: 201.26277923583984 seconds
Result: 0-1
r n . . k b . r
p p p . p p . p
. . . . . . p .
. . . p P . . .
. . . . q . . .
. . . . . . . .
P P P P . n P P
R N B K . B N .

1. e4  Nc6 
2. d4  d5 
3. exd5  Qxd5 
4. Nf3  Bg4 
5. Be2  Qf5 
6. 0-0  O-O-O 
7. c3  e5 
8. Nh4  Bxe2 
9. Qxe2  Qe6 
10. dxe5  Qxe5 
11. Qxe5  Nxe5 
12. Nd2  Rd5 
13. Nhf3  Nd3 
14. Ne4  Ra5 
15. Rd1  Nxc1 
16. Rdxc1  Be7 
17. Re1  Nf6 
18. Neg5  Bd8 
19. Nxf7  Rg8 
20. Nxd8  Rxd8 
21. Nd4  Ra6 
22. Re7  Re8 
23. Rxg7  c5 
24. Nb5  Rb6 
25. c4  a6 
26. Nc3  Rxb2 
27. Na4  Rxa2 
28. Nb6+  Kb8 
29. Rb1  Ree2 
30. h3  Reb2 
31. Rxb2  Rxb2 
32. Error parsing move .Na4: invalid san: '.Na4'
Error parsing move .Na4: invalid san: '.Na4'
Error parsing move .Rf7: invalid san: '.Rf7'
Error parsing move .Na4: invalid san: '.Na4'
Error parsing move .Nd7+: invalid san: '.Nd7+'
<__main__.GPTPlayer object at 0x7fd80fa09150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa09150>

Game over. Total time: 522.2954969406128 seconds
Result: *
. k . . . . . .
. p . . . . R p
p N . . . n . .
. . p . . . . .
. . P . . . . .
. . . . . . . P
. r . . . P P .
. . . . . . K .

1. e4  c6 
2. d4  d5 
3. Nc3  a6 
4. Nf3  Bg4 
5. h3  Bxf3 
6. Qxf3  Nf6 
7. Bg5  Nxe4 
8. Nxe4  dxe4 
9. Qxe4  h6 
10. Bd2  a5 
11. 0-0-0  e6 
12. Kb1  a4 
13. a3  Qb6 
14. Ka1  Bd6 
15. Bc4  Be7 
16. Rhe1  Bf6 
17. Bc3  O-O 
18. g4  Rd8 
19. f4  Nd7 
20. g5  hxg5 
21. fxg5  Be7 
22. Bxe6  c5 
23. Bxf7+  Kxf7 
24. Qxe7+  Kg6 
25. dxc5  Nf6 
26. gxf6  Rd7 
27. Rxd7  gxf6 
28. Qh7+  Kg5 
29. Rg7+  Kf4 
30. Qe4# 
Game over. Total time: 454.1293911933899 seconds
Result: 1-0
r . . . . . . .
. p . . . . R .
. q . . . p . .
. . P . . . . .
p . . . Q k . .
P . B . . . . P
. P P . . . . .
K . . . R . . .

1. e4  c6 
2. d4  g6 
3. Nc3  Qc7 
4. Nf3  a6 
5. Bd3  d6 
6. 0-0  Bg4 
7. h3  Bxf3 
8. Qxf3  Nd7 
9. Re1  Bg7 
10. Be3  Ngf6 
11. Rad1  e6 
12. Bg5  O-O 
13. Qe3  b5 
14. Bh6  Bxh6 
15. Qxh6  e5 
16. dxe5  Nxe5 
17. Qf4  Ne8 
18. Ne2  Qb6 
19. c3  Rd8 
20. Bb1  a5 
21. Nd4  b4 
22. Qg5  Ng7 
23. Qe3  Nc4 
24. Qc1  d5 
25. exd5  cxd5 
26. b3  Na3 
27. cxb4  Nxb1 
28. Qxb1  axb4 
29. Qd3  Rd6 
30. Re5  Ne6 
31. Nxe6  fxe6 
32. Qe2  Rf6 
33. Rd2  Rc6 
34. Kh2  Qa7 
35. Qe1  Qb6 
36. Qe2  Qc7 
37. g3  Rxf2+ 
38. Qxf2  Qxe5 
39. Re2  Qd6 
40. Qa7  e5 
41. Qa8+  Kg7 
42. Qb7+  Rc7 
43. Qb8  h5 
44. h4  e4 
45. Rf2  e3 
46. Re2  d4 
47. Qb5  d3 
48. Rxe3  d2 
49. Rd3  d1=Q 
50. Rxd1  Rc2+ 
51. Kh3  Qe6+ 
52. g4  Qe3# 
Game over. Total time: 870.9750797748566 seconds
Result: 0-1
. . . . . . . .
. . . . . . k .
. . . . . . p .
. Q . . . . . p
. p . . . . P P
. P . . q . . K
P . r . . . . .
. . . R . . . .

1. e4  c6 
2. d4  a6 
3. Nc3  h6 
4. Nf3  d5 
5. Bd3  dxe4 
6. Nxe4  Nf6 
7. 0-0  Bg4 
8. Re1  e6 
9. h3  Bxf3 
10. Qxf3  Nbd7 
11. Bf4  Nxe4 
12. Bxe4  Nf6 
13. Bxc6+  bxc6 
14. Qxc6+  Nd7 
15. d5  Rc8 
16. Qxa6  Nc5 
17. Qb5+  Qd7 
18. Qxd7+  Kxd7 
19. dxe6+  Nxe6 
20. Rad1+  Kc6 
21. Be5  Rg8 
22. Re3  Kb5 
23. Rb3+  Ka6 
24. c3  g5 
25. Rd7  Bc5 
26. Rxf7  Rcf8 
27. Rxf8  Rxf8 
28. Bg3  Bb6 
29. Error parsing move Ke2: illegal san: 'Ke2' in 5r2/8/kb2n2p/6p1/8/1RP3BP/PP3PP1/6K1 w - - 2 29
Ra3+  Kb5 
30. Rb3+  Kc6 
31. Ra3  h5 
32. Ra4  Rf5 
33. Re4  Nf4 
34. Bxf4  gxf4 
35. Kf1  f3 
36. g4  Ra5 
37. Ke1  Kd5 
38. Rb4  Bc5 
39. Rb8  hxg4 
40. hxg4  Ra7 
41. Error parsing move Ke2: illegal san: 'Ke2' in 1R6/r7/8/2bk4/6P1/2P2p2/PP3P2/4K3 w - - 1 41
Error parsing move Ke2: illegal san: 'Ke2' in 1R6/r7/8/2bk4/6P1/2P2p2/PP3P2/4K3 w - - 1 41
Error parsing move Ke2: illegal san: 'Ke2' in 1R6/r7/8/2bk4/6P1/2P2p2/PP3P2/4K3 w - - 1 41
Error parsing move Ke2: illegal san: 'Ke2' in 1R6/r7/8/2bk4/6P1/2P2p2/PP3P2/4K3 w - - 1 41
Error parsing move Ke2: illegal san: 'Ke2' in 1R6/r7/8/2bk4/6P1/2P2p2/PP3P2/4K3 w - - 1 41
<__main__.GPTPlayer object at 0x7fd80fa09150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa09150>

Game over. Total time: 672.513206243515 seconds
Result: *
. R . . . . . .
r . . . . . . .
. . . . . . . .
. . b k . . . .
. . . . . . P .
. . P . . p . .
P P . . . P . .
. . . . K . . .

1. e4  e6 
2. d4  a6 
3. Nf3  b5 
4. Bd3  c5 
5. c3  Nf6 
6. 0-0  Bb7 
7. Re1  h6 
8. Nbd2  Qc7 
9. Nf1  c4 
10. Bc2  d6 
11. Ng3  g6 
12. Be3  Bg7 
13. h3  Nfd7 
14. Qd2  Nf6 
15. a4  Nbd7 
16. axb5  axb5 
17. Rxa8+  Bxa8 
18. Ra1  Ke7 
19. d5  Nc5 
20. Nd4  Qb6 
21. dxe6  Bxe4 
22. Nxe4  Nfxe4 
23. Bxe4  fxe6 
24. Nc6+  Kd7 
25. Ra7+  Qxa7 
26. Nxa7  Nd3 
27. Bxd3  Ra8 
28. Bxg6  Bf6 
29. Bxh6  Rxa7 
30. Qf4  Ra1+ 
31. Kh2  Rf1 
32. Qxf6  Rc1 
33. Bxc1  Kc6 
34. Qxe6  Kc7 
35. Bf4  Kb6 
36. Qxd6+  Kb7 
37. Be4+  Ka7 
38. Qc7+  Ka6 
39. Bb7+  Ka7 
40. Bc8+  Ka8 
41. Qb7# 
Game over. Total time: 572.13609623909 seconds
Result: 1-0
k . B . . . . .
. Q . . . . . .
. . . . . . . .
. p . . . . . .
. . p . . B . .
. . P . . . . P
. P . . . P P K
. . . . . . . .

1. e4  c5 
2. Nf3  g6 
3. d4  cxd4 
4. Nxd4  Nc6 
5. Nc3  a6 
6. Be3  Rb8 
7. Qd2  Bg7 
8. 0-0-0  Ra8 
9. h4  h5 
10. f3  d6 
11. Bc4  Nf6 
12. Bb3  Bd7 
13. Kb1  Qc7 
14. Bg5  Nxd4 
15. Qxd4  O-O 
16. Qd2  Rfb8 
17. g4  b5 
18. Bxf6  exf6 
19. gxh5  Qa5 
20. hxg6  b4 
21. Nd5  Rb7 
22. gxf7+  Kh8 
23. Rdg1  Bb5 
24. Rxg7  Kxg7 
25. Rg1+  Kh7 
26. Nxf6+  Kh8 
27. Qh6# 
Game over. Total time: 419.99493956565857 seconds
Result: 1-0
r . . . . . . k
. r . . . P . .
p . . p . N . Q
q b . . . . . .
. p . . P . . P
. B . . . P . .
P P P . . . . .
. K . . . . R .

1. e4  e5 
2. Nf3  Nf6 
3. Nxe5  Nxe4 
4. Qe2  Ng5 
5. Nc6+  Be7 
6. Nxe7  Qxe7 
7. Qxe7+  Kxe7 
8. d4  Ne4 
9. Bd3  Kd8 
10. 0-0  f5 
11. Re1  d5 
12. f3  Nf6 
13. Bg5  c6 
14. Re5  h6 
15. Bxf6+  gxf6 
16. Re1  a5 
17. Nc3  Ra7 
18. Na4  b5 
19. Nc5  Rg8 
20. Re2  a4 
21. Rae1  h5 
22. Ne6+  Ke7 
23. Bxf5  Kf7 
24. Nf4  Bxf5 
25. Nxh5  b4 
26. Ng3  Rg5 
27. Re8  Rb7 
28. Rh8  Bxc2 
29. Ree8  Nd7 
30. Rc8  Bg6 
31. Rxc6  Nb6 
32. Rd8  Nc4 
33. b3  Ke7 
34. Rh8  Na5 
35. Ra6  axb3 
36. axb3  Nxb3 
37. Raa8  Nxd4 
38. Rhg8  b3 
39. Error parsing move Ke1: illegal san: 'Ke1' in R5R1/1r2k3/5pb1/3p2r1/3n4/1p3PN1/6PP/6K1 w - - 0 39
Rxg6  b2 
40. Rxg5  b1=Q+ 
41. Nf1  fxg5 
42. Ra4  Ne2+ 
43. Kf2  Nd4 
44. Ke3  Qb3+ 
45. Kxd4  Qb2+ 
46. Ke3  Rb3# 
Game over. Total time: 771.758782863617 seconds
Result: 0-1
. . . . . . . .
. . . . k . . .
. . . . . . . .
. . . p . . p .
R . . . . . . .
. r . . K P . .
. q . . . . P P
. . . . . N . .

1. e4  c5 
2. Nf3  d6 
3. d4  cxd4 
4. Nxd4  Nf6 
5. Nc3  a6 
6. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c4a10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e98d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e8e10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4ea3d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4eab50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80fa09150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa09150>

Game over. Total time: 37829.550538778305 seconds
Result: *
r n b q k b . r
. p . . p p p p
p . . p . n . .
. . . . . . . .
. . . N P . . .
. . N . . . . .
P P P . . P P P
R . B Q K B . R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c5910>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e1390>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e3590>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e2550>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4bd410>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80fa09150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa09150>

Game over. Total time: 0.02375030517578125 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd82bf764d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f47d5d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c4390>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd82ed02890>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f47e190>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80fa09150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa09150>

Game over. Total time: 0.01387333869934082 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Nf3  Nf6 
2. d4  d5 
3. c4  e6 
4. Nc3  Be7 
5. Bg5  h6 
6. Bxf6  Bxf6 
7. h3  O-O 
8. Rc1  c6 
9. e4  dxe4 
10. Nxe4  c5 
11. Nxf6+  Qxf6 
12. Bd3  cxd4 
13. O-O  Nc6 
14. a3  a5 
15. Re1  Rd8 
16. Rb1  a4 
17. Be4  Bd7 
18. Qc2  Be8 
19. b3  axb3 
20. Qxb3  Na5 
21. Qb4  Bc6 
22. Bxc6  bxc6 
23. Re5  c5 
24. Rxc5  Rdb8 
25. Qxb8+  Rxb8 
26. Rxb8+  Kh7 
27. Rxa5  d3 
28. Re5  Qf4 
29. Rb1  Qxc4 
30. a4  Qxa4 
31. Ree1  Qc2 
32. Rf1  f6 
33. Rfd1  e5 
34. Ne1  Qe2 
35. Rxd3  e4 
36. Re3  Qc4 
37. g3  f5 
38. Reb3  Qe2 
39. Ng2  Qc2 
40. h4  Qd2 
41. Rb6  Qc2 
42. Ne1  Qd2 
43. Ng2  Qc2 
44. Rb8  Qd2 
45. R8b2  Qc3 
46. Rb7  Qd2 
47. Ne3  f4 
48. gxf4  Qd8 
49. Ra7  Qxh4 
50. Rxg7+  Kh8 
51. Rb8+  Kxg7 
52. Nf5+ 1-0, player has resigned
<__main__.GPTPlayer object at 0x7fd80f47fcd0> resigned with result: *

Game over. Total time: 880.3528738021851 seconds
Result: *
. R . . . . . .
. . . . . . k .
. . . . . . . p
. . . . . N . .
. . . . p P . q
. . . . . . . .
. . . . . P . .
. . . . . . K .

1. d4  Nf6 
2. Nf3  g6 
3. Nbd2  Bg7 
4. e4  d6 
5. Bc4  O-O 
6. a4  Nxe4 
7. O-O  Nxd2 
8. Bxd2  Bg4 
9. h3  Bxf3 
10. Qxf3  c6 
11. c3  d5 
12. Bd3  Nd7 
13. Bg5  f6 
14. Bh4  Qb6 
15. a5  Qxb2 
16. Be2  Qd2 
17. Bg3  e5 
18. Rfd1  Qh6 
19. c4  e4 
20. Qa3  f5 
21. Bd6  Rfe8 
22. Qb3  b6 
23. cxd5  c5 
24. axb6  axb6 
25. Rxa8  Rxa8 
26. dxc5  bxc5 
27. Qb5  Rd8 
28. Be7  Rb8 
29. Qxd7  Qf4 
30. Qe6+  Kh8 
31. d6  Be5 
32. Bf6+  Bxf6 
33. Qxf6+  Kg8 
34. Bc4# 
Game over. Total time: 569.9636926651001 seconds
Result: 1-0
. r . . . . k .
. . . . . . . p
. . . P . Q p .
. . p . . p . .
. . B . p q . .
. . . . . . . P
. . . . . P P .
. . . R . . K .

1. e4  e5 
2. Be2  Nf6 
3. Nf3  Nc6 
4. d4  exd4 
5. Nxd4  Nxe4 
6. Nxc6  bxc6 
7. O-O  Bc5 
8. Bf3  Ng5 
9. Bxc6  dxc6 
10. Qxd8+  Kxd8 
11. Rd1+  Bd6 
12. Bxg5+  f6 
13. Bc1  Bf5 
14. Bf4  Ke7 
15. Rd4  Bxc2 
16. Nd2  Rhd8 
17. Bxd6+  cxd6 
18. h3  Rab8 
19. b3  d5 
20. Re1+  Kf7 
21. Ra4  Rb7 
22. Rc1  Bf5 
23. Rxc6  Bd7 
24. Rd6  Ke7 
25. Raa6  Bc8 
26. Rxd8  Kxd8 
27. Nf3  Rc7 
28. Ra5  Bb7 
29. Rxa7  Kc8 
30. Ra5  Rc1+ 
31. Kh2  Rc2 
32. Kg3  Rc3 
33. h4  d4 
34. h5 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f0510>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f2050>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e9810>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f1310>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f3990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 772.2114708423615 seconds
Result: *
. . k . . . . .
. b . . . . p p
. . . . . p . .
R . . . . . . P
. . . p . . . .
. P r . . N K .
P . . . . P P .
. . . . . . . .

1. Nf3  Nf6 
2. d4  d5 
3. c4  e6 
4. Bg5  Be7 
5. cxd5  exd5 
6. Qc2  O-O 
7. Nc3  c6 
8. e3 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f2790>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f512dd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f511710>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4bd390>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e2c90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 192.59167766571045 seconds
Result: *
r n b q . r k .
p p . . b p p p
. . p . . n . .
. . . p . . B .
. . . P . . . .
. . N . P N . .
P P Q . . P P P
R . . . K B . R

1. c4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f48b450>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4a0110>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f5102d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c6490>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f47f810>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 16.420164108276367 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . P . . . . .
. . . . . . . .
P P . P P P P P
R N B Q K B N R

1. c4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e0ed0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f512850>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e0750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f3ad0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f48a5d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 16.34531044960022 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . P . . . . .
. . . . . . . .
P P . P P P P P
R N B Q K B N R

1. Nf3 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4a0310>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f5138d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f3910>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f2910>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e9010>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 16.34559726715088 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . N . .
P P P P P P P P
R N B Q K B . R

1. e4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4d92d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4da710>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f2690>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f0450>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4ebb10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 16.345282316207886 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B Q K B N R

1. d4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4bcf50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4bd250>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e9f50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f2350>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f9fbc50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 16.34533381462097 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . P . . . .
. . . . . . . .
P P P . P P P P
R N B Q K B N R

1. d4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80fa09850>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f2c10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f1ed0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4ebb10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f9e7350>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 16.343621969223022 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . P . . . .
. . . . . . . .
P P P . P P P P
R N B Q K B N R

1. e4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80fdeb990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4eb010>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f32d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd82bf75bd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4ac910>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 16.345041751861572 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B Q K B N R

1. c4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f04d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4eb190>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80fdeb990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e3ad0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4bf790>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 16.340902090072632 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . P . . . . .
. . . . . . . .
P P . P P P P P
R N B Q K B N R

1. Nf3 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4ea850>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f3bd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f2a50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80fd666d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e8790>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 16.34932565689087 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . N . .
P P P P P P P P
R N B Q K B . R

1. d4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f24d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4bed90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f511850>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4da250>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f3e10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 16.349188804626465 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . P . . . .
. . . . . . . .
P P P . P P P P
R N B Q K B N R

1. d4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e9e10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f510b10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4a0a10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f510810>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4ae110>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f47fcd0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f47fcd0>

Game over. Total time: 16.572467803955078 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . P . . . .
. . . . . . . .
P P P . P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52ac10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f511510>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4eba50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f48ab50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f528d10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.030626773834228516 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52dc90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e8a90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f513cd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f5285d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4bce10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.03237032890319824 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd82ea5e990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52bbd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f510a10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c5f50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e2750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.021654844284057617 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e3d50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd82bf40090>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f5127d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f529950>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4ad390>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.02034902572631836 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd82e18d8d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f511750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c5fd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f5297d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f47ef10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.02036738395690918 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e3d90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52a790>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd82ea5e990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f511210>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f9e6150>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.020425081253051758 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4adad0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f512a50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80fa0a510>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f529390>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f06d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.02080702781677246 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f47e990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f528c10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd82ea5cd50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f512c90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4bcad0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.020641565322875977 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f512410>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c6a50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52bbd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4bf490>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f47de10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.020830869674682617 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52ae50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c7ad0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80fd649d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f511cd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4aeb10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.020778656005859375 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f3310>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4ad8d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f510a90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52b550>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f47f850>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.02130126953125 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c5150>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52a5d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4bc790>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e32d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4a1690>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.02070021629333496 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f19d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52bcd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c4750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4a3dd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4893d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.020415782928466797 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c7dd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f9ac550>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e1990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4eac50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4eb790>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.020143747329711914 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4a3b90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4d9c90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4be450>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f47d1d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f9e72d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80f9f01d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80f9f01d0>

Game over. Total time: 0.01940774917602539 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. g3 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4a1690>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e9790>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f528f50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52a650>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4a3e10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80fa0a1d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa0a1d0>

Game over. Total time: 16.447681665420532 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . P .
P P P P P P . P
R N B Q K B N R

1. Nf3  Nf6 
2. d4  d5 
3. g3  c6 
4. Nbd2  Bf5 
5. e3  e6 
6. a3  Nbd7 
7. c4  Be7 
8. Bg2  O-O 
9. b3  Ne4 
10. Nxe4  Bxe4 
11. O-O  a5 
12. Qe2  a4 
13. cxd5  cxd5 
14. b4  Nb6 
15. Bb2  Nc4 
16. Ne5  Bxg2 
17. Kxg2  Rc8 
18. h4  Bd6 
19. Nd3  b6 
20. Rac1  Qd7 
21. Kg1  Rc7 
22. Rfe1  Rfc8 
23. Kh1  h6 
24. Kg1  Qb5 
25. Red1  Be7 
26. Re1  Bf6 
27. Red1  Rc6 
28. Rc3  R8c7 
29. Rc2  Nd6 
30. Rdc1  Rxc2 
31. Rxc2  Rxc2 
32. Qxc2  Qc4 
33. Qd1  b5 
34. Qb1  Ne4 
35. Qd1  Be7 
36. Ne5  Qc7 
37. Qd3  Bd6 
38. Kf1  f6 
39. Nf3  Qc4 
40. Ne1  Kf7 
41. Ke2  g5 
42. hxg5  hxg5 
43. Kf3  f5 
44. Ke2  g4 
45. Qxc4  dxc4 
46. Bc1  Nc3+ 
47. Kf1  Ke7 
48. Bd2  Nb1 
49. Bc1  Kd7 
50. Bb2  Kc6 
51. Ke2  Kd5 
52. Kd1  Ke4 
53. Kc1 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f1f10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52b550>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f0690>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e3a50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f52f550>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80fa0a1d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa0a1d0>

Game over. Total time: 6350.293876886368 seconds
Result: *
. . . . . . . .
. . . . . . . .
. . . b p . . .
. p . . . p . .
p P p P k . p .
P . . . P . P .
. B . . . P . .
. n K . N . . .

1. e3 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f540dd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e18d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4a3ad0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f0c90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f512a50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80fa0a1d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa0a1d0>

Game over. Total time: 16.345595359802246 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . P . . .
P P P P . P P P
R N B Q K B N R

1. Nf3 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f0d10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f489650>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e0e90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f529550>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4ae3d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80fa0a1d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa0a1d0>

Game over. Total time: 16.36235213279724 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . N . .
P P P P P P P P
R N B Q K B . R

1. d4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f510a10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4a1690>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f1090>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f5410d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f1f10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80fa0a1d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa0a1d0>

Game over. Total time: 16.3581964969635 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . P . . . .
. . . . . . . .
P P P . P P P P
R N B Q K B N R

1. d4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e9310>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f510a50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e31d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f543750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4f2090>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80fa0a1d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa0a1d0>

Game over. Total time: 16.43783402442932 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . P . . . .
. . . . . . . .
P P P . P P P P
R N B Q K B N R

1. e4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e3f90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80fd71110>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4c4a10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f48b9d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd80f4e0050>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fd80fa0a1d0> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fd80fa0a1d0>

Game over. Total time: 16.3406822681427 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B Q K B N R

1. d4  Nf6 
2. Bf4  d5 
3. Nd2  c5 
4. c3  Nc6 
5. Rc1  cxd4 
6. cxd4  Nxd4 
7. Ngf3  Nc6 
8. Ne5  Qb6 
9. Qa4  Bd7 
10. Nxd7  Nxd7 
11. Nb3  e5 
12. Be3  d4 
13. Bd2  Bb4 
14. g4  O-O 
15. Bg2  Bxd2+ 
16. Nxd2  Nc5 
17. Qc2  Ne6 
18. h4  Nf4 
19. Qe4  Qxb2 
20. Rb1  Qxa2 
21. Rxb7  Rac8 
22. g5  d3 
23. Rb1  Nd4 
24. Qxe5  Nxg2+ 
25. Kf1  dxe2+ 
26. Kg1  Qxd2 
27. Qxd4  Qxd4 
28. Rh3  e1=Q+ 
29. Rxe1  Nxe1 
30. Re3  Rc1 
31. Re4  Qxe4 
32. g6  Qg2# 
Game over. Total time: 515.1498897075653 seconds
Result: 0-1
. . . . . r k .
p . . . . p p p
. . . . . . P .
. . . . . . . .
. . . . . . . P
. . . . . . . .
. . . . . P q .
. . r . n . K .

1. d4  Nf6 
2. c4  e6 
3. Nf3  d5 
4. g3  Bb4+ 
5. Nc3  O-O 
6. Qb3  c5 
7. dxc5  Na6 
8. cxd5  exd5 
9. Be3  Ne4 
10. Qc2  Bf5 
11. Qc1  Qa5 
12. Bg2  Nxc3 
13. bxc3  Bxc3+ 
14. Bd2  Bxd2+ 
15. Qxd2  Qxd2+ 
16. Kxd2  Nxc5 
17. Rhd1  Rac8 
18. Nh4  Be4 
19. Bxe4  dxe4 
20. Ke1  g6 
21. Ng2  Rfd8 
22. Nf4  Kg7 
23. Rdb1  b6 
24. Rb4  f5 
25. a4  Kf6 
26. h4  h6 
27. Kf1  g5 
28. hxg5+  hxg5 
29. Nh5+  Kg6 
30. g4  fxg4 
31. Ng3  Re8 
32. a5  Rc6 
33. axb6  axb6 
34. Rc1  Rf6 
35. Kg1  Ree6 
36. Rc3  Rf4 
37. e3  Rf3 
38. Rbc4  Ref6 
39. Rc2  Nd3 
40. Nxe4  Re6 
41. R2c3  Ne5 
42. Rb4  Rf8 
43. Kh2  Nf3+ 
44. Kg2  Rh8 
45. Ng3  Rh2+ 
46. Kf1  Rh4 
47. Rc2  Rd6 
48. Rc8  Rd1+ 
49. Ke2  Rd2+ 
50. Kf1  Rd1+ 
51. Ke2  Re1+ 
52. Kd3  Ne5+ 
53. Kd2  Ra1 
54. Rxb6+  Kf7 
55. Rc7+  Nd7 
56. Rxd7+  Ke8 
57. Rg7  Ra2+ 
58. Kc3  Kf8 
59. Nf5  Ra8 
60. Rbb7  Rh1 
61. Rbf7+  Ke8 
62. Re7+  Kf8 
63. Ref7+  Ke8 
64. Nd6+  Kd8 
65. Nb7+  Ke8 
66. Nd6+  Kd8 
67. Rd7# 
Game over. Total time: 1109.57683467865 seconds
Result: 1-0
r . . k . . . .
. . . R . . R .
. . . N . . . .
. . . . . . p .
. . . . . . p .
. . K . P . . .
. . . . . P . .
. . . . . . . r

1. e4  e5 
2. Bc4  Nf6 
3. Qe2  Nc6 
4. Nc3  Nd4 
5. Qd1  Bc5 
6. d3  d6 
7. Nb5  Bg4 
8. Qd2  O-O 
9. f3  Bd7 
10. a4  a6 
11. Nxd4  Bxd4 
12. Bb3  b5 
13. a5  c5 
14. Ba2  b4 
15. Ne2  Qxa5 
16. Nxd4  exd4 
17. Bxf7+  Rxf7 
18. Rxa5  Bb5 
19. c4  bxc3 
20. Qd1  Bc6 
21. Qc2  Rb7 
22. bxc3  dxc3 
23. Ra3  d5 
24. g4  d4 
25. g5  Nd7 
26. O-O  Ne5 
27. Qa2+  Kh8 
28. Rxa6  Rxa6 
29. Qxa6  Rb8 
30. f4  Ra8 
31. fxe5  Rxa6 
32. Rf8# 
Game over. Total time: 538.0205597877502 seconds
Result: 1-0
. . . . . R . k
. . . . . . p p
r . b . . . . .
. . p . P . P .
. . . p P . . .
. . p P . . . .
. . . . . . . P
. . B . . . K .

1. d4  Nf6 
2. g3  d5 
3. Bg2  e6 
4. Nf3  Be7 
5. Ne5  O-O 
6. c4  c6 
7. Qc2  Nbd7 
8. Nxd7  Bxd7 
9. O-O  Rc8 
10. c5  b6 
11. Nd2  bxc5 
12. Nf3  cxd4 
13. Nxd4  c5 
14. Nb3  Ba4 
15. Qc3  Qb6 
16. Na5  c4 
17. Bd2  Rb8 
18. b3  Bb4 
19. Qxb4  Qxb4 
20. Bxb4  Rxb4 
21. bxa4  Rxa4 
22. Nc6  Ra6 
23. Ne7+  Kh8 
24. Rab1  Rxa2 
25. Bf3  g6 
26. Rb7  Kg7 
27. Kg2  g5 
28. h3  h5 
29. Nc6  g4 
30. hxg4  hxg4 
31. Rc7  gxf3+ 
32. Kxf3  a5 
33. Rb1  Ne4 
34. Rh1  Ra3+ 
35. Kg2  Ra2 
36. Rh4  Rxe2 
37. Rg4+  Kh6 
38. Rh4+  Kg5 
39. Ra7  Rxf2+ 
40. Kg1  Ra2 
41. Ne5  Nxg3 
42. Rh7  Kf4 
43. Nxc4  dxc4 
44. Rb7  c3 
45. Rh6  c2 
46. Rh4+  Kg5 
47. Rh5+  Kxh5 
48. Rc7  c1=Q+ 
49. Rxc1  Ne2+ 
50. Kg2  Nxc1+ 
51. Kh3  Rg8 
Game over. Total time: 843.2150869369507 seconds
Result: 1/2-1/2
. . . . . . r .
. . . . . p . .
. . . . p . . .
p . . . . . . k
. . . . . . . .
. . . . . . . K
r . . . . . . .
. . n . . . . .

1. e4  e5 
2. Nf3  Nc6 
3. Bb5  a6 
4. Bxc6  dxc6 
5. Qe2  f6 
6. Nc3  c5 
7. O-O  Bd6 
8. a4  Ne7 
9. Nh4  O-O 
10. a5  Be6 
11. b3  Qd7 
12. Nd1  Nc6 
13. Nb2  Nd4 
14. Qd3  Rad8 
15. Re1  Qf7 
16. Nf3  Nc6 
17. h3  Nb4 
18. Qc3  Qg6 
19. Nc4  Bxh3 
20. Nh4  Qg4 
21. Qxh3  Qxh3 
22. gxh3  Nxc2 
23. Bb2  Nxa1 
24. Rxa1  Be7 
25. Kg2  Rd3 
26. Bc3  Rfd8 
27. Nf5  Kf7 
28. Nfe3  g6 
29. Kf3  Ke6 
30. Nb2  R3d7 
31. Ke2  f5 
32. d3  Bg5 
33. Nd5  Rf7 
34. Rg1  Bh4 
35. Rg2  Rdf8 
36. Be1  f4 
37. Rg4  Bd8 
38. Nc4  g5 
39. Bc3  h5 
40. Rg1  Bf6 
41. Bb2  Rg7 
42. Nxf6  Kxf6 
43. Bxe5+  Kg6 
44. Bxg7  Kxg7 
45. Rxg5+  Kh6 
46. h4  f3+ 
47. Kd2  Rf4 
48. Rg8  Rxh4 
49. Rg1  Rh2 
50. Ke3  Rg2 
51. Rc1  h4 
52. Ra1  h3 
53. Rh1  h2 
54. Kxf3  Rg1 
55. Rxh2+  Kg6 
56. Rg2+  Rxg2 
57. Kxg2  Kf6 
58. Kf3  Ke6 
59. Kf4  Kf6 
60. Kg3  Kg5 
61. Kf3  Kf6 
62. Kg3  Kg5 
63. f3  Kf6 
64. f4  Ke6 
65. f5+  Kf6 
66. Kf4  Kf7 
67. e5  Ke7 
68. f6+  Ke6 
69. Ke4  Kf7 
70. Kf5  Kf8 
71. Kf4  Kf7 
72. Kf5  Kf8 
73. Ke4  Kf7 
74. Kf3  Ke6 
75. Kf4  Kf7 
76. Nd2  Ke6 
77. Ne4  Kd5 
78. Kf5  Kd4 
79. Kf4  Kxd3 
80. f7  Kc2 
81. f8=Q  Kxb3 
82. e6  Kb4 
83. e7  Kxa5 
84. Qf5  b6 
85. e8=Q  Kb4 
86. Nxc5  bxc5 
87. Qe3  Kb5 
88. Qb3+  Kc6 
89. Qe4+  Kd7 
90. Qbe6+  Kd8 
91. Q4d5# 
Game over. Total time: 1446.0181984901428 seconds
Result: 1-0
. . . k . . . .
. . p . . . . .
p . . . Q . . .
. . p Q . . . .
. . . . . K . .
. . . . . . . .
. . . . . . . .
. . . . . . . .

1. Nf3  Nf6 
2. g3  g6 
3. Bg2  Bg7 
4. Nc3  O-O 
5. e4  d6 
6. h3  c5 
7. a4  Nc6 
8. Nh4  e5 
9. d3  Be6 
10. Nd5  h6 
11. Nxf6+  Qxf6 
12. Be3  Qe7 
13. Qe2  Kh7 
14. Rd1  Nd4 
15. Bxd4  cxd4 
16. c4  dxc3 
17. bxc3  Rac8 
18. Qc2  Rc5 
19. c4  a6 
20. Rb1  b5 
21. axb5  axb5 
22. Rxb5  Rxb5 
23. cxb5  Rc8 
24. Qb1  Qg5 
25. O-O  Qd2 
26. b6  Rb8 
27. b7  Qa5 
28. Qb2  Qa6 
29. Ra1  Qxb7 
30. Qc2  Qb2 
31. Qxb2  Rxb2 
32. Nf3  Bf6 
33. Ra6  Be7 
34. Rc6  Kg7 
35. Bf1  Kf8 
36. h4  Ke8 
37. Kg2  Kd7 
38. Rc1  Bd8 
39. d4  Bb6 
40. Ra1  exd4 
41. Ne1  Rd2 
42. Rc1  d5 
43. Bd3  dxe4 
44. Bxe4  d3 
45. Nxd3  f5 
46. Rc6  fxe4 
47. Ne5+  Ke7 
48. Rxb6  e3 
49. Nxg6+  Kf7 
50. Ne5+  Kf6 
51. Ng4+  Ke7 
52. Rb7+  Kd6 
53. Rb6+  Ke7 
54. Rb7+  Kd6 
55. Nxe3  Bd5+ 
56. Nxd5  Kxd5 
57. Rd7+ 1-0, player has resigned
<__main__.GPTPlayer object at 0x7fd80fa0a1d0> resigned with result: *

Game over. Total time: 957.8190062046051 seconds
Result: *
. . . . . . . .
. . . R . . . .
. . . . . . . p
. . . k . . . .
. . . . . . . P
. . . . . . P .
. . . r . P K .
. . . . . . . .

1. d4  Nf6 
2. g3  d5 
3. Bg2  c6 
4. Nf3  Bf5 
5. a4  e6 
6. c4  h6 
7. O-O  Be7 
8. a5  O-O 
9. Nc3  Nbd7 
10. Qb3  Qc8 
11. h3  Ne4 
12. Bf4  Nxc3 
13. Qxc3  Be4 
14. c5  a6 
15. Nd2  Bxg2 
16. Kxg2  Bf6 
17. Nf3  Re8 
18. Qc2  e5 
19. Bxe5  Nxe5 
20. dxe5  Bxe5 
21. e3  Bf6 
22. Ra4  Qd7 
23. Rd1  Rad8 
24. h4  Qe6 
25. Rd3  Rd7 
26. Rd1  Rde7 
27. Rd3  Rd7 
28. Rb4  Bd8 
29. Rdb3  Ree7 
30. Ra4  Re8 
31. Rab4  Ree7 
32. Ra3  Re8 
33. h5  Bf6 
34. Qd1  Qe7 
35. Rab3  Qxc5 
36. Nd4  Bxd4 
37. exd4  Qxa5 
38. Rxb7  Rxb7 
39. Rxb7  Qe1 
40. Qxe1  Rxe1 
41. Rb6  Re4 
42. Rb8+  Kh7 
43. b3  Rxd4 
44. Ra8  Rb4 
45. Rxa6  Rxb3 
46. Rxc6  Rb7 
47. Rc5  Rd7 
48. Ra5  g6 
49. Kf3  gxh5 
50. Ke3  Kg6 
51. Ke2  Kf5 
52. f3  Kxe5 
53. Ra4  d4 
54. Kd3  Kf6 
55. Ra2  Kg5 
56. Rh2  f5 
57. Rh1  f4 
58. gxf4+  Kxf4 
59. Rxh5  Rd6 
60. Rh3  Kg5 
61. Rh1  h5 
62. Rh2  h4 
63. Rh1  Kf4 
64. Rxh4+  Kxf3 
65. Rh1  Kf4 
66. Ra1  Ke5 
67. Re1+  Kd5 
68. Re8  Ra6 
69. Rf8  Ra3+ 
70. Ke2  Ra2+ 
71. Kd3  Ra3+ 
72. Ke2  Ra2+ 
73. Ke1  Ra1+ 
74. Ke2  Ra2+ 
75. Kf1  Ra1+ 
76. Ke2  Ra2+ 
77. Kd3  Ra3+ 
78. Kd2  Ra2+ 
79. Kc1  Ra1+ 
80. Kc2  Ra2+ 
81. Kb3  Ra5 
82. Rf5+  Ke4 
83. Rxa5  d3 
84. Kc3  Ke3 
85. Re5+  Kf4 
86. Rd5  Ke4 
87. Rd8  Ke3 
88. Rd7  Ke4 
89. Rxd3 1-0, player has resigned
<__main__.GPTPlayer object at 0x7fd80fa0a1d0> resigned with result: *

Game over. Total time: 1496.2712726593018 seconds
Result: *
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . k . . .
. . K R . . . .
. . . . . . . .
. . . . . . . .

1. d4  Nf6 
2. Bf4  d5 
3. c3  c5 
4. Nf3  Nc6 
5. dxc5  e6 
6. b4  a5 
7. a3  axb4 
8. cxb4  Nxb4 
9. e4  Nxe4 
10. Nc3  Nxc3 
11. Qb3  Nc6 
12. Qxc3  Qa5 
13. Rc1  Qxc3+ 
14. Rxc3  Ra5 
15. Bd3  Rxc5 
16. Rb3  f6 
17. O-O  e5 
18. Re1  Be7 
19. Be3  d4 
20. Bc1  Na5 
21. Rb1  Rc3 
22. Bb5+  Kf7 
23. Bd2  Rxa3 
24. Rec1  Nb3 
25. Bc4+  Be6 
26. Rxb3  Rxb3 
27. Bxe6+  Kxe6 
28. Rd1  Ra8 
29. Re1  Kd5 
30. Kf1  Ra2 
31. Bg5  Rbb2 
32. Bf4  Rxf2+ 
33. Kg1  Rxg2+ 
34. Kh1  Rgf2 
35. h4  Rxf3 
36. Bd2  Rxd2 
37. Rc1  Bc5 
38. Ra1  d3 
39. Rd1  Rh3# 
Game over. Total time: 631.7040612697601 seconds
Result: 0-1
. . . . . . . .
. p . . . . p p
. . . . . p . .
. . b k p . . .
. . . . . . . P
. . . p . . . r
. . . r . . . .
. . . R . . . K

