1. e4  Nf6 
2. e5  Ne4 
3. Ke2  g6 
4. Ke3  d5 
5. Ke2  d4 
6. Ke1  Bg7 
7. Ke2  Nc5 
8. Ke1  Nc6 
9. Ke2  Qd5 
10. Ke1  Qxe5+ 
11. Qe2  Qxe2+ 
12. Kxe2  d3+ 
13. Ke1  dxc2 
14. Ke2  Bg4+ 
15. Ke1  cxb1=R 
16. Error parsing move Ke2: illegal san: 'Ke2' in r3k2r/ppp1ppbp/2n3p1/2n5/6b1/8/PP1P1PPP/RrB1KBNR w kq - 0 16
Error parsing move Ke2: illegal san: 'Ke2' in r3k2r/ppp1ppbp/2n3p1/2n5/6b1/8/PP1P1PPP/RrB1KBNR w kq - 0 16
Error parsing move Ke2: illegal san: 'Ke2' in r3k2r/ppp1ppbp/2n3p1/2n5/6b1/8/PP1P1PPP/RrB1KBNR w kq - 0 16
Error parsing move Ke2: illegal san: 'Ke2' in r3k2r/ppp1ppbp/2n3p1/2n5/6b1/8/PP1P1PPP/RrB1KBNR w kq - 0 16
Error parsing move Ke2: illegal san: 'Ke2' in r3k2r/ppp1ppbp/2n3p1/2n5/6b1/8/PP1P1PPP/RrB1KBNR w kq - 0 16
<__main__.GPTPlayer object at 0x7fa26d79c750> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d79c750>

Game over. Total time: 254.16404724121094 seconds
Result: *
r . . . k . . r
p p p . p p b p
. . n . . . p .
. . n . . . . .
. . . . . . b .
. . . . . . . .
P P . P . P P P
R r B . K B N R

1. e4  d5 
2. exd5  Bf5 
3. Nc3  c6 
4. dxc6  Nxc6 
5. Nf3  Rc8 
6. d4  Nf6 
7. Bb5  a6 
8. Bxc6+  Rxc6 
9. 0-0  Nd5 
10. Ne5  Nxc3 
11. bxc3  Rxc3 
12. Bd2  Rxc2 
13. Be3  Qd5 
14. Rc1  Rxc1 
15. Qxc1  f6 
16. Nf3  Kd8 
17. Qb2  Qb5 
18. Qc3  Be4 
19. Nd2  Bc6 
20. Rc1  Qd5 
21. f3  Ke8 
22. Nb3  Qd6 
23. Na5  e6 
24. Nxc6  Qxc6 
25. Qxc6+  bxc6 
26. Rxc6  Kd7 
27. Rxa6  Bd6 
28. Ra7+  Kc6 
29. Rxg7  f5 
30. Ra7  Rc8 
31. Ra6+  Kd5 
32. Kf1  Bxh2 
33. Ke2  Rc2+ 
34. Ke1  Rb2 
35. Error parsing move Ke2: illegal san: 'Ke2' in 8/7p/R3p3/3k1p2/3P4/4BP2/Pr4Pb/4K3 w - - 4 35
Error parsing move Ke1: illegal san: 'Ke1' in 8/7p/R3p3/3k1p2/3P4/4BP2/Pr4Pb/4K3 w - - 4 35
Error parsing move Ke1: illegal san: 'Ke1' in 8/7p/R3p3/3k1p2/3P4/4BP2/Pr4Pb/4K3 w - - 4 35
Error parsing move Ke2: illegal san: 'Ke2' in 8/7p/R3p3/3k1p2/3P4/4BP2/Pr4Pb/4K3 w - - 4 35
Error parsing move Ke1: illegal san: 'Ke1' in 8/7p/R3p3/3k1p2/3P4/4BP2/Pr4Pb/4K3 w - - 4 35
<__main__.GPTPlayer object at 0x7fa26d79c750> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d79c750>

Game over. Total time: 572.0845336914062 seconds
Result: *
. . . . . . . .
. . . . . . . p
R . . . p . . .
. . . k . p . .
. . . P . . . .
. . . . B P . .
P r . . . . P b
. . . . K . . .

1. e4  d5 
2. exd5  Nf6 
3. d4  Qxd5 
4. Nc3  Qa5 
5. Nf3  Bg4 
6. h3  Bd7 
7. Ne5  Be6 
8. Bc4  Bxc4 
9. Nxc4  Qa6 
10. Qe2  Qc6 
11. 0-0  Nd5 
12. Nxd5  Qxd5 
13. Bf4  e6 
14. Ne3  Qe4 
15. Bxc7  Be7 
16. Qb5+  Nd7 
17. d5  a6 
18. Qxb7  O-O 
19. d6  Qxb7 
20. dxe7  Rfc8 
21. Bd6  h6 
22. c4  Nb8 
23. c5  Nc6 
24. Nc4  Ra7 
25. Nb6  Rca8 
26. Nxa8  Qxa8 
27. Rfd1  Rd7 
28. Rac1  a5 
29. Rc3  f6 
30. Re3  Nxe7 
31. Rxe6  Ng6 
32. Rd4  Qb7 
33. b3  Rd8 
34. Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error parsing move Ke2: illegal san: 'Ke2' in 3r2k1/1q4p1/3BRpnp/p1P5/3R4/1P5P/P4PP1/6K1 w - - 1 34
Rde4  Qd5 
35. Re2  Ne5 
36. Re7  Ng6 
37. Error parsing move None: expected string or bytes-like object, got 'NoneType'
R7e4  Rc8 
38. Kh2  Ra8 
39. Kg1  Rc8 
40. Kh2  Kh7 
41. Kg1  Qc6 
42. Kh2  Qd5 
43. Kg1  f5 
44. Re6  a4 
45. bxa4  Qd1+ 
46. Kh2  Qd4 
47. a5  Qc4 
48. a6  Qa4 
49. a7  Qxa7 
50. c6  Rxc6 
51. Bg3  Rxe6 
52. Rxe6  f4 
53. Bxf4  Qxa2 
54. Re4  Qd5 
55. Error parsing move Ke3: illegal san: 'Ke3' in 8/6pk/6np/3q4/4RB2/7P/5PPK/8 w - - 2 55
f3  Qxe4 
56. fxe4  Nxf4 
57. Kg3  Ne6 
58. Kf3  Kg6 
59. Ke3  Nc5 
60. Ke2  Kf6 
61. Ke3  Ke5 
62. Ke2  Nd7 
63. Ke3  Nb6 
64. Ke2  Nd7 
65. Ke3  Nf6 
66. Ke2  Nxe4 
67. Ke3  Kf5 
68. Ke2  h5 
69. Ke3  Ke5 
70. Ke2  h4 
71. Ke3  Ng5 
72. Ke2  Kf4 
73. Kf2  Nh7 
74. Ke2  Kg3 
75. Ke3  Ng5 
76. Ke2  Nf7 
77. Ke3  Ng5 
78. Ke2  Kxg2 
79. Ke3  Nxh3 
80. Ke4  Nf4 
81. Ke5  Kg3 
82. Ke4  h3 
83. Ke5  g6 
84. Ke4  g5 
85. Ke5  h2 
86. Ke4  h1=Q+ 
87. Ke5  Qd5+ 
88. Kf6  Qe6+ 
89. Kg7  Qe7+ 
90. Kh6  Qf7 
91. Kxg5  Ne6+ 
92. Kh6  Qg7+ 
93. Kh5  Nf4# 
Game over. Total time: 26059.956231594086 seconds
Result: 0-1
. . . . . . . .
. . . . . . q .
. . . . . . . .
. . . . . . . K
. . . . . n . .
. . . . . . k .
. . . . . . . .
. . . . . . . .

1. e4  e5 
2. Nf3  d5 
3. Nxe5  Be6 
4. exd5  Qxd5 
5. d4  Nd7 
6. Nc3  Bb4 
7. Nxd7  Bxd7 
8. Be2  Qxg2 
9. Bf3  Bxc3+ 
10. bxc3  Qg6 
11. Bxb7  Rb8 
12. Qe2+  Kd8 
13. Be4  Bf5 
14. Bxf5  Qxf5 
15. 0-0  Ne7 
16. Ba3  Ng6 
17. Rae1  Rb6 
18. Qe4  Rb5 
19. Qxf5  Rxf5 
20. Re3  Re8 
21. Rfe1  Rxe3 
22. Rxe3  Ra5 
23. Bb4  Rxa2 
24. Re2  Ra1+ 
25. Kg2  Nf4+ 
26. Kf3  Nxe2 
27. Ke3  Nxd4 
28. Ke4  Ne6 
29. Ke5  Kc8 
30. Ke4  Ng5+ 
31. Ke3  Re1+ 
32. Kd2  Re4 
33. Kd3  Rh4 
34. Ke3  Ne6 
35. Ke2  Kb8 
36. Ke3  g6 
37. Ke2  Ng7 
38. Ke3  Ka8 
39. Ke2  a6 
40. Ke3  g5 
41. Ke2  Kb8 
42. Ke3  h6 
43. Ke2  Rh3 
44. Ke1  Rxh2 
45. Ke2  h5 
46. Ke3  Ka8 
47. Ke2  Kb8 
48. Ke3  h4 
49. Ke2  Ne6 
50. Ke3  h3 
51. Ke2  Rg2 
52. Ke3  h2 
53. Ke2  h1=Q 
54. Ke3  Rg1 
55. Ke2  Qe4+ 
56. Kd2  Qf3 
57. Error parsing move Ke1: illegal san: 'Ke1' in 1k6/2p2p2/p3n3/6p1/1B6/2P2q2/2PK1P2/6r1 w - - 6 57
Error parsing move Ke1: illegal san: 'Ke1' in 1k6/2p2p2/p3n3/6p1/1B6/2P2q2/2PK1P2/6r1 w - - 6 57
Error parsing move Ke1: illegal san: 'Ke1' in 1k6/2p2p2/p3n3/6p1/1B6/2P2q2/2PK1P2/6r1 w - - 6 57
Error parsing move Ke1: illegal san: 'Ke1' in 1k6/2p2p2/p3n3/6p1/1B6/2P2q2/2PK1P2/6r1 w - - 6 57
1/2-1/2, player has resigned
<__main__.GPTPlayer object at 0x7fa26d79c750> resigned with result: *

Game over. Total time: 920.3336496353149 seconds
Result: *
. k . . . . . .
. . p . . p . .
p . . . n . . .
. . . . . . p .
. B . . . . . .
. . P . . q . .
. . P K . P . .
. . . . . . r .

1. e4  e5 
2. Nf3  d6 
3. d4  Nf6 
4. Nc3  Nc6 
5. Bb5  Bd7 
6. 0-0  Be7 
7. Re1  O-O 
8. Bxc6  Bxc6 
9. dxe5  Nd7 
10. exd6  Bf6 
11. Nd5  cxd6 
12. Nxf6+  Nxf6 
13. Bg5  h6 
14. Bxf6  Qxf6 
15. Qd4  Rfe8 
16. Qxf6  gxf6 
17. Nd2  Rad8 
18. c4  a5 
19. f3  a4 
20. Kf2  Bd7 
21. Ke3  f5 
22. Kd4  Re5 
23. exf5  Bxf5 
24. Rxe5  dxe5+ 
25. Ke3  a3 
26. b3  Rd3+ 
27. Ke2  f6 
28. Ne4  Rd4 
29. Ke3  Kg7 
30. Ke2  Bxe4 
31. Ke3  Bg6 
32. Ke2  Bd3+ 
33. Ke3  Bg6 
34. Ke2  f5 
35. Ke3  h5 
36. Ke2  f4 
37. Ke1  Kf6 
38. Ke2  h4 
39. Ke1  e4 
40. Ke2  Bh5 
41. Ke1  e3 
42. Ke2  Rd2+ 
43. Ke1  h3 
44. gxh3  Bxf3 
45. Kf1  Rxh2 
46. Ke1  b5 
47. 0-1, player has resigned
<__main__.GPTPlayer object at 0x7fa26d79c750> resigned with result: *

Game over. Total time: 744.5293264389038 seconds
Result: *
. . . . . . . .
. . . . . . . .
. . . . . k . .
. p . . . . . .
. . P . . p . .
p P . . p b . P
P . . . . . . r
R . . . K . . .

1. e4  e6 
2. d4  d5 
3. Nc3  Nf6 
4. Bg5  dxe4 
5. Nxe4  c5 
6. Nxc5  Be7 
7. Nf3  O-O 
8. Nb3  h6 
9. Bh4  Nd5 
10. Bxe7  Qxe7 
11. Bd3  b6 
12. O-O  Qc7 
13. Re1  Rd8 
14. c3  Nd7 
15. Qe2  Bb7 
16. g3  Rac8 
17. Rad1  Kh8 
18. Bb1  Rb8 
19. Nbd2  Rbc8 
20. Ne4  N5f6 
21. Ned2  Ba8 
22. Ne5  Rf8 
23. Ndf3  Qb7 
24. Qd3  Rcd8 
25. Qe3  Nxe5 
26. dxe5  Rxd1 
27. Rxd1  Qxf3 
28. Qxf3  Bxf3 
29. Rd3  Be4 
30. exf6  Bxd3 
31. fxg7+  Kxg7 
32. Bxd3  Rd8 
33. Bc4  Rd2 
34. b4  Rc2 
35. Bb3  Rxc3 
36. Kg2  Rc1 
37. Kf3  Rh1 
38. Ke3  a6 
39. Ke2  Kf8 
40. Ke3  Ke7 
41. Ke2  a5 
42. Ke3  Rf1 
43. Ke2  Ra1 
44. Ke3  Rb1 
45. Ke2  Rg1 
46. Ke3  Rh1 
47. Ke2  Rxh2 
48. Ke3  Rh1 
49. Ke2  f5 
50. Ke3  axb4 
51. Ke2  Rc1 
52. Ke3  Rh1 
53. Ke2  Rb1 
54. Ke3  h5 
55. Ke2  Ra1 
56. Ke3  Rc1 
57. Ke2  Rb1 
58. Ke3  h4 
59. Ke2  h3 
60. Ke3  h2 
61. Ke2  h1=Q 
62. Ke3  Rc1 
63. Ke2  Qe4+ 
64. Kd2  Qe1+ 
65. Kd3  Qe4+ 
66. Kd2  Qe1+ 
67. Kd3  e5 
68. Error parsing move Ke3: illegal san: 'Ke3' in 8/4k3/1p6/4pp2/1p6/1B1K2P1/P4P2/2r1q3 w - - 0 68
Bd5  Qc3+ 
69. Ke2  Re1# 
Game over. Total time: 1063.4088063240051 seconds
Result: 0-1
. . . . . . . .
. . . . k . . .
. p . . . . . .
. . . B p p . .
. p . . . . . .
. . q . . . P .
P . . . K P . .
. . . . r . . .

1. e4  e6 
2. d4  d5 
3. Nc3  c6 
4. Nf3  Bb4 
5. e5  Ne7 
6. a3  Ba5 
7. Bd3  h6 
8. 0-0  Bxc3 
9. bxc3  b6 
10. a4  Ba6 
11. Ba3  Qc7 
12. Bd6  Qd7 
13. a5  Qb7 
14. axb6  Bxd3 
15. Qxd3  Nc8 
16. Bc5  axb6 
17. Rxa8  Qxa8 
18. Bb4  Nd7 
19. c4  dxc4 
20. Qxc4  Qb7 
21. Ra1  c5 
22. dxc5  bxc5 
23. Bxc5  Qc6 
24. Ra5  f6 
25. exf6  Rg8 
26. Nd4  Qe4 
27. Qxe6+  Qxe6 
28. Nxe6  Nxc5 
29. Nxc5  Kf7 
30. fxg7  Re8 
31. Kf1  Nd6 
32. Ra7+  Kg8 
33. Nd7  Ne4 
34. Ke2  Kxg7 
35. Ke3  Re7 
36. Ke2  Nf6+ 
37. Kd3  Nxd7 
38. c4  Nc5+ 
39. Error parsing move Ke3: illegal san: 'Ke3' in 8/R3r1k1/7p/2n5/2P5/3K4/5PPP/8 w - - 1 39
Error parsing move Ke3: illegal san: 'Ke3' in 8/R3r1k1/7p/2n5/2P5/3K4/5PPP/8 w - - 1 39
Error parsing move Ke3: illegal san: 'Ke3' in 8/R3r1k1/7p/2n5/2P5/3K4/5PPP/8 w - - 1 39
Error parsing move Ke3: illegal san: 'Ke3' in 8/R3r1k1/7p/2n5/2P5/3K4/5PPP/8 w - - 1 39
Error parsing move Ke3: illegal san: 'Ke3' in 8/R3r1k1/7p/2n5/2P5/3K4/5PPP/8 w - - 1 39
<__main__.GPTPlayer object at 0x7fa26d79c750> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d79c750>

Game over. Total time: 638.0702261924744 seconds
Result: *
. . . . . . . .
R . . . r . k .
. . . . . . . p
. . n . . . . .
. . P . . . . .
. . . K . . . .
. . . . . P P P
. . . . . . . .

1. e4  e6 
2. d4  a6 
3. Nf3  d5 
4. Nc3  dxe4 
5. Nxe4  Nd7 
6. Bd3  Ngf6 
7. 0-0  Nxe4 
8. Bxe4  Bd6 
9. c4  Nf6 
10. Bc2  Be7 
11. Qd3  c5 
12. Bg5  cxd4 
13. Rad1  b5 
14. cxb5  axb5 
15. Nxd4  Rxa2 
16. Qxb5+  Nd7 
17. Nc6  Qb6 
18. Qxb6  Nxb6 
19. Bxe7  Bd7 
20. Ba3  Bxc6 
21. Bb3  Bd5 
22. Bxa2  Bxa2 
23. Rd6  Nd5 
24. Ra1  O-O 
25. Rxa2  Ra8 
26. Ra1  h5 
27. Error parsing move Ke2: illegal san: 'Ke2' in r5k1/5pp1/3Rp3/3n3p/8/B7/1P3PPP/R5K1 w - - 0 27
Error parsing move Ke2: illegal san: 'Ke2' in r5k1/5pp1/3Rp3/3n3p/8/B7/1P3PPP/R5K1 w - - 0 27
Rd1  Ra4 
28. R6xd5  f5 
29. Rd8+  Kf7 
30. R1d7+  Kf6 
31. Rf8+  Ke5 
32. Bd6+  Kd5 
33. Bf4+  Kc5 
34. Rc8+  Kb5 
35. Rb7+  Ka6 
36. Ra8+  Kxb7 
37. Rxa4  Kc8 
38. Ra7  g5 
39. Bxg5  h4 
40. Bxh4  f4 
41. Re7  Kb8 
42. Rxe6  Kb7 
43. Re4  Kc8 
44. Rxf4  Kb8 
45. Rf7  Ka8 
46. Error parsing move Ke2: illegal san: 'Ke2' in k7/5R2/8/8/7B/8/1P3PPP/6K1 w - - 3 46
0-1, player has resigned
<__main__.GPTPlayer object at 0x7fa26d79c750> resigned with result: *

Game over. Total time: 748.8523550033569 seconds
Result: *
k . . . . . . .
. . . . . R . .
. . . . . . . .
. . . . . . . .
. . . . . . . B
. . . . . . . .
. P . . . P P P
. . . . . . K .

1. e4  c5 
2. Nf3  d6 
3. d4  Nd7 
4. Nc3  a6 
5. a4  g6 
6. Be2  cxd4 
7. Nxd4  b6 
8. 0-0  Ngf6 
9. f4  Bg7 
10. Bf3  e5 
11. Nc6  Qc7 
12. Nb4  Qc5+ 
13. Kh1  Qxb4 
14. Nd5  Nxd5 
15. Qxd5  Rb8 
16. Bd2  Qd4 
17. Qxd4  exd4 
18. Bb4  Nc5 
19. e5  O-O 
20. exd6  a5 
21. Ba3  Bf5 
22. Rac1  h5 
23. Rfd1  h4 
24. h3  Rbc8 
25. Bxc5  Rxc5 
26. c3  Rd8 
27. cxd4  Rc2 
28. Rxc2  Bxc2 
29. Rd2  Bf5 
30. Bc6  Bh6 
31. Rf2  Bf8 
32. Re2  Bxd6 
33. Re8+  Rxe8 
34. Bxe8  Bxf4 
35. d5  Be4 
36. Bc6  Bc2 
37. Kg1  Kf8 
38. Kf2  g5 
39. Ke2  Bf5 
40. Ke1  Bd3 
41. Kd1  f5 
42. Ke1  Ke7 
43. Kf2  Kd6 
44. Ke1  Be4 
45. Ke2  Ke7 
46. Ke1  Bb1 
47. Ke2  Kd6 
48. Ke1  Bc2 
49. Ke2  Be4 
50. Ke1  Be5 
51. Ke2  Bxg2 
52. Ke1  Bxh3 
53. Ke2  Bg4+ 
54. Ke1  Bxb2 
55. Error parsing move Ke2: illegal san: 'Ke2' in 8/8/1pBk4/p2P1pp1/P5bp/8/1b6/4K3 w - - 0 55
Error parsing move Ke2: illegal san: 'Ke2' in 8/8/1pBk4/p2P1pp1/P5bp/8/1b6/4K3 w - - 0 55
Error parsing move Ke2: illegal san: 'Ke2' in 8/8/1pBk4/p2P1pp1/P5bp/8/1b6/4K3 w - - 0 55
Error parsing move Ke2: illegal san: 'Ke2' in 8/8/1pBk4/p2P1pp1/P5bp/8/1b6/4K3 w - - 0 55
Error parsing move Ke2: illegal san: 'Ke2' in 8/8/1pBk4/p2P1pp1/P5bp/8/1b6/4K3 w - - 0 55
<__main__.GPTPlayer object at 0x7fa26d79c750> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d79c750>

Game over. Total time: 909.2322781085968 seconds
Result: *
. . . . . . . .
. . . . . . . .
. p B k . . . .
p . . P . p p .
P . . . . . b p
. . . . . . . .
. b . . . . . .
. . . . K . . .

1. e4  e5 
2. Nf3  Nf6 
3. Nxe5  Nxe4 
4. d4  d5 
5. Bd3  Nd7 
6. Nxd7  Qxd7 
7. 0-0  Bd6 
8. c4  O-O 
9. cxd5  Re8 
10. Nc3  Nf6 
11. Bg5  Qd8 
12. Qf3  a5 
13. Rfe1  Bg4 
14. Bxf6  Rxe1+ 
15. Rxe1  Bxh2+ 
16. Kh1  Qxf6 
17. Qxf6  gxf6 
18. Kxh2  a4 
19. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48f450>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48e510>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4c89d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4dd650>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4df4d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d79c750> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d79c750>

Game over. Total time: 38043.8875079155 seconds
Result: *
r . . . . . k .
. p p . . p . p
. . . . . p . .
. . . P . . . .
p . . P . . b .
. . N B . . . .
P P . . . P P K
. . . . R . . .

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4dd450>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4cb550>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48ecd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a89d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d79db50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d79c750> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d79c750>

Game over. Total time: 0.013824701309204102 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4dd450>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a6fd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e2d50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4ca410>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4c96d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d79c750> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d79c750>

Game over. Total time: 0.018826723098754883 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d7b33d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d850790>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4ddb10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4db510>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48c850>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d79c750> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d79c750>

Game over. Total time: 0.010951995849609375 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d7b2a50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4ddb10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e2a90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fd310>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e2c10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d79c750> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d79c750>

Game over. Total time: 0.03579974174499512 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26db06550>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4de150>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48ee50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fec10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa28c75a750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d79c750> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d79c750>

Game over. Total time: 0.028092384338378906 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. g3  e5 
2. d3  d5 
3. Nf3  Nc6 
4. a3  Nf6 
5. Nc3  d4 
6. Na2  Be7 
7. e3  O-O 
8. exd4  exd4 
9. Bg2  Be6 
10. O-O  Qd7 
11. b4  a6 
12. Bb2  Rad8 
13. Qe2  Rfe8 
14. Qd2  Bh3 
15. Rfe1  Bxg2 
16. Kxg2  Qd5 
17. Qd1  Bd6 
18. Rxe8+  Rxe8 
19. Nc1  g5 
20. Kg1  g4 
21. Ne1  Ne5 
22. c4  dxc3 
23. Bxc3  Ne4 
24. Bxe5  Bxe5 
25. Qxg4+  Bg7 
26. Nf3  Nf6 
27. Qf4  Nh5 
28. Qg4  Nf6 
29. Qf4  Nh5 
30. Qg4  Nf6 
31. Qf4  Nh5 
32. Qg4  Nf6 
33. Qf4  Nh5 
34. Qg4  Nf6 
Game over. Total time: 574.4836030006409 seconds
Result: 1/2-1/2
. . . . r . k .
. p p . . p b p
p . . . . n . .
. . . q . . . .
. P . . . . Q .
P . . P . N P .
. . . . . P . P
R . N . . . K .

1. c4  e5 
2. g3  Nf6 
3. Nf3  Nc6 
4. Nc3  Bb4 
5. Qc2  O-O 
6. a3  Bxc3 
7. Qxc3  Re8 
8. d4  exd4 
9. Qb3  d5 
10. c5  Ne4 
11. Qd1  Qf6 
12. Bg2  d3 
13. Qxd3  Nxc5 
14. Qc2  Qe7 
15. O-O  Bg4 
16. Be3  Ne4 
17. Rfd1  Rad8 
18. b4  a6 
19. Qb3  Qf6 
20. Nd4  Nxd4 
21. Bxd4  Qg6 
22. f3  c5 
23. bxc5  Nxc5 
24. Qa2  Ne6 
25. fxg4  Qxg4 
26. e3  Ng5 
27. Qb2  f6 
28. Kh1  b5 
29. Rab1  Ne4 
30. Qa2  Kh8 
31. Kg1  h5 
32. Rbc1  h4 
33. gxh4  Qxh4 
34. Bf3  Ng5 
35. Qg2  Nxf3+ 
36. Qxf3  Re4 
37. h3  Rde8 
38. Kh1  Qh6 
39. Kh2  Rh4 
40. Rc5  Ree4 
41. Rc8+  Kh7 
42. Qf5+  Qg6 
43. Rh8+  Kxh8 
44. Qxg6  Rh6 
45. Qf7  Reh4 
46. Rg1  Rxh3+ 
47. Kg2  Rh2+ 
48. Kf1  Rh7 
49. Qe8# 
Game over. Total time: 822.3216695785522 seconds
Result: 1-0
. . . . Q . . k
. . . . . . p r
p . . . . p . .
. p . p . . . .
. . . B . . . .
P . . . P . . .
. . . . . . . r
. . . . . K R .

1. e4  c5 
2. Nf3  d6 
3. d4  cxd4 
4. Qxd4  Nc6 
5. Qd1  Nf6 
6. Bd3  g6 
7. Nc3  Bg7 
8. h3  O-O 
9. Be3  d5 
10. Nxd5  Nxd5 
11. exd5  Qxd5 
12. O-O  Bxb2 
13. Bh6  Rd8 
14. Rb1  Bf6 
15. Re1  Qxa2 
16. Nd2  Ne5 
17. Ne4  Nxd3 
18. Nxf6+  exf6 
19. Qxd3  Bf5 
20. Qf3  Qd5 
21. Re8+  Rxe8 
22. Qxd5  Bxc2 
23. Qd4  Re6 
24. Rf1  b6 
25. h4  Rae8 
26. f3  a5 
27. Rc1  Bb3 
28. Qd7  a4 
29. Kh2  R6e7 
30. Rc8 1-0, player has resigned
<__main__.GPTPlayer object at 0x7fa28cd1a890> resigned with result: *

Game over. Total time: 512.346905708313 seconds
Result: *
. . R . r . k .
. . . Q r p . p
. p . . . p p B
. . . . . . . .
p . . . . . . P
. b . . . P . .
. . . . . . P K
. . . . . . . .

1. d4  Nf6 
2. a3  e6 
3. Bg5  c5 
4. Nc3  cxd4 
5. Bxf6  Qxf6 
6. Na2  Nc6 
7. g3  d5 
8. Bg2  Bc5 
9. Nb4  Nxb4 
10. axb4  Bxb4+ 
11. c3  dxc3 
12. Qa4+  Bd7 
13. Qxb4  cxb2 
14. Rb1  Rc8 
15. Nh3  Rc1+ 
16. Kd2  Rc4 
17. Qxb2 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fa6d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d518910>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d51a550>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fb890>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4dea10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 503.6524543762207 seconds
Result: *
. . . . k . . r
p p . b . p p p
. . . . p q . .
. . . p . . . .
. . r . . . . .
. . . . . . P N
. Q . K P P B P
. R . . . . . R

1. Nf3 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d519a10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d51be50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4d85d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d518f90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d51b250>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 16.349567890167236 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . N . .
P P P P P P P P
R N B Q K B . R

1. d4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a58d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fd590>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a6450>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4d9210>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d519810>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 16.424662590026855 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . P . . . .
. . . . . . . .
P P P . P P P P
R N B Q K B N R

1. c4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d518a90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e1dd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d519350>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4dae50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a6e90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 16.350591897964478 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . P . . . . .
. . . . . . . .
P P . P P P P P
R N B Q K B N R

1. e4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a8450>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a9750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a5850>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4d8c10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d519350>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 16.352898359298706 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B Q K B N R

1. c4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48c850>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d5195d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fcc50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48d490>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a54d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 16.351298332214355 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . P . . . . .
. . . . . . . .
P P . P P P P P
R N B Q K B N R

1. e4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a6710>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4dbdd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48f810>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d518d10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fb050>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 16.428624629974365 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B Q K B N R

1. Nf3 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d519a10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fef50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4d8990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a6e90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4cbcd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 16.44997000694275 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . N . .
P P P P P P P P
R N B Q K B . R

1. Nf3 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fdfd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa28cec9c50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d519a50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4ca150>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d518590>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 16.35439395904541 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . N . .
P P P P P P P P
R N B Q K B . R

1. e4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48fcd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4aac90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4ca990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4ddd90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48f890>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 16.3454372882843 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B Q K B N R

1. c4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4c8f50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d519a90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d52a210>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d519950>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a6f90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 16.342780590057373 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . P . . . . .
. . . . . . . .
P P . P P P P P
R N B Q K B N R

1. e4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fe1d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d52ac90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4ff1d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a7750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d5184d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa28cd1a890> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa28cd1a890>

Game over. Total time: 16.342915296554565 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d535810>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d52aa90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4c8f10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fb950>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48f050>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.019751787185668945 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e0890>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48c810>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fb390>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa28bf30490>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d528d50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.018931865692138672 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e0a90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4f84d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e0550>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48ff10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4aa010>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.018604278564453125 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d7b1c10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48e210>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d528d10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4f8750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d7b3a90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.018789291381835938 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fe5d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4f8090>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d52b850>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4cb150>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a6490>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.017553091049194336 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4aa010>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48c790>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d529010>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4f9110>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d51b750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.018207550048828125 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fcc10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fa6d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a5e90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d519bd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d535810>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.018344640731811523 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a81d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48dfd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e1f10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4f9ed0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d537d50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.018250465393066406 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fb090>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a71d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d537510>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4abbd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d545850>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.01802802085876465 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48d710>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d51a490>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d534ad0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fb090>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d544190>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.01759624481201172 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e1110>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4fa210>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a8210>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d545b90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d48d9d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.017800331115722656 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4abad0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e1f10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d537350>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d548990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d546790>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.015466690063476562 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d544f10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d5355d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d51a250>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d51be50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d519b90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.012582063674926758 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d5350d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d535cd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d544a50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4a5810>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d546750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.012501955032348633 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d536190>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d536a50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d518f50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d79d050>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d51ab50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d4a6150> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d4a6150>

Game over. Total time: 0.013754606246948242 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R

1. c4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa28cec9c50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d546f50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d7b1c50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d546050>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d535990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d51a990> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d51a990>

Game over. Total time: 16.349750518798828 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . P . . . . .
. . . . . . . .
P P . P P P P P
R N B Q K B N R

1. d4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d7b2310>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4f8350>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4f8510>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d5343d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d547050>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d51a990> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d51a990>

Game over. Total time: 16.351038932800293 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . P . . . .
. . . . . . . .
P P P . P P P P
R N B Q K B N R

1. c4  e5 
2. Nf3  Nc6 
3. d4  exd4 
4. g3  Bc5 
5. Nbd2  d6 
6. Nb3  Qf6 
7. a3  Nge7 
8. Bg2  O-O 
9. Bg5  Qg6 
10. O-O  Re8 
11. Bxe7  Rxe7 
12. Nbxd4  Nxd4 
13. Nxd4  a5 
14. e3  c6 
15. b4  Bxd4 
16. Qxd4  Bf5 
17. Rfd1  Rd7 
18. b5  c5 
19. Qf4  Re8 
20. Rd2  Be4 
21. f3  Bc2 
22. Rc1  Bb3 
23. e4  Qe6 
24. Bf1  a4 
25. h4  Qe5 
26. Bh3  Rdd8 
27. Kf2  Qxf4 
28. gxf4  Kf8 
29. Bg4  Ke7 
30. h5  g6 
31. Bh3  Kf6 
32. Rc3  gxh5 
33. b6  Ke7 
34. Bf1  Rg8 
35. Rdd3  h4 
36. Rd5  Rg6 
37. Rf5  Rdg8 
38. Rh5  Rg1 
39. Rxh4  R8g7 
40. Rh6  R1g6 
41. Rh2  Rg8 
42. Rc1  R6g7 
43. Rh6  Rd8 
44. Re1  Kf8 
45. f5  Kg8 
46. f4  Rg4 
47. Be2  Rxf4+ 
48. Ke3  Kg7 
49. Rhh1  Rxe4+ 
50. Kxe4  Re8+ 
51. Kd5  Re5+ 
52. Kxd6 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e2b90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d529750>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4aabd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4c9a50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d54ad50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d51a990> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d51a990>

Game over. Total time: 6336.096670389175 seconds
Result: *
. . . . . . . .
. p . . . p k p
. P . K . . . .
. . p . r P . .
p . P . . . . .
P b . . . . . .
. . . . B . . .
. . . . R . . R

1. d4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4ab990>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d528e10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e2e10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d51bbd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d529b50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d51a990> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d51a990>

Game over. Total time: 16.419284105300903 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . P . . . .
. . . . . . . .
P P P . P P P P
R N B Q K B N R

1. e4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4aaad0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26db5db50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e1450>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d544ed0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4c9150>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d51a990> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d51a990>

Game over. Total time: 16.344465970993042 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B Q K B N R

1. e4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4e3090>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d529450>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d544bd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d544710>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d529b50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d51a990> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d51a990>

Game over. Total time: 16.34309673309326 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B Q K B N R

1. c4 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa289d6e810>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4dab50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d51a350>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4cab50>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d52bb10>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d51a990> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d51a990>

Game over. Total time: 16.33964991569519 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . P . . . . .
. . . . . . . .
P P . P P P P P
R N B Q K B N R

1. Nf3 Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d547cd0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d537810>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d534d90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d5452d0>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
Error while getting GPT response: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa26d4aba90>: Failed to resolve 'api.openai.com' ([Errno -2] Name or service not known)"))
Error parsing move None: expected string or bytes-like object, got 'NoneType'
<__main__.GPTPlayer object at 0x7fa26d51a990> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d51a990>

Game over. Total time: 16.438932180404663 seconds
Result: *
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . N . .
P P P P P P P P
R N B Q K B . R

1. c4  e5 
2. Nf3  Nc6 
3. d4  exd4 
4. Nxd4  Bb4+ 
5. Bd2  Bxd2+ 
6. Qxd2  Nf6 
7. Nc3  O-O 
8. O-O-O  Re8 
9. g3  Ne5 
10. e4  d6 
11. Be2  Bh3 
12. Rhe1  a6 
13. f4  Ned7 
14. Qe3  Nc5 
15. e5  Ng4 
16. Qf3  dxe5 
17. Nc6  Qf6 
18. Ne7+  Qxe7 
19. b4  e4 
20. Bf1  Bxf1 
21. Qxg4  Nd3+ 
22. Kd2  Nxe1 
23. Nd5  Qd6 
24. Qe2  Nf3+ 
25. Ke3  Bxe2 
26. c5  Qh6 
27. Nxc7  Bxd1 
28. h4  Qf6 
29. Kf2  Qb2+ 
30. Kf1  Qe2# 
Game over. Total time: 470.8454134464264 seconds
Result: 0-1
r . . . r . k .
. p N . . p p p
p . . . . . . .
. . P . . . . .
. P . . p P . P
. . . . . n P .
P . . . q . . .
. . . b . K . .

1. d4  Nf6 
2. h3  d5 
3. Bf4  c5 
4. c3  Nc6 
5. Nf3  Qb6 
6. Qc2  cxd4 
7. Nbd2  dxc3 
8. Qxc3  Bf5 
9. e3  e6 
10. Qb3  Bb4 
11. a3  Bxd2+ 
12. Nxd2  Qxb3 
13. Nxb3  e5 
14. Bh2  O-O 
15. Nc5  b6 
16. Nb3  Rac8 
17. Bb5  Bc2 
18. Nc1  Nd4 
19. exd4  exd4 
20. O-O  Ne4 
21. Be5  Nd2 
22. Bxd4  Nxf1 
23. Bxf1  Rfe8 
24. Ne2  Bd3 
25. Ng3  Bxf1 
26. Nxf1  Rc4 
27. Rd1  Re2 
28. Ne3  Rc8 
29. g4  f6 
30. Kf1  Rxe3 
31. fxe3  Kf7 
32. Kg2  Ke6 
33. Kg3  Rc2 
34. Rf1  h6 
35. Rb1  g5 
36. Ra1  f5 
37. Rf1  fxg4 
38. hxg4  Re2 
39. Rf6+  Kd7 
40. Rxh6  Re1 
41. a4  Rg1+ 
42. Kf3  Rf1+ 
43. Kg2  Ra1 
44. Rh7+  Kc6 
45. Rxa7  b5 
46. Rg7  bxa4 
47. Kf3  Rf1+ 
48. Ke2  Rg1 
49. Kf3  Rf1+ 
50. Kg2  Rd1 
51. Rg6+  Kb5 
52. Rxg5  Kc4 
53. Kf2  Rd2+ 
54. Kf3  Rd1 
55. Ke2  Rg1 
56. Kf2  Rd1 
57. Rg8  Rd2+ 
58. Kf3  Rd1 
59. Kf2  Rd2+ 
60. Kf3  Rd1 
61. g5  Rg1 
62. Ke2  Rg2+ 
63. Kf3  Rg1 
64. g6  Kb3 
65. Kf2  Rg5 
66. g7  Rg6 
67. Rb8+  Kc2 
68. g8=Q  Rxg8 
69. Rxg8 Error parsing move Kxb2: illegal san: 'Kxb2' in 6R1/8/8/3p4/p2B4/4P3/1Pk2K2/8 b - - 0 69
Error parsing move Kxb2: illegal san: 'Kxb2' in 6R1/8/8/3p4/p2B4/4P3/1Pk2K2/8 b - - 0 69
Error parsing move Kxb2: illegal san: 'Kxb2' in 6R1/8/8/3p4/p2B4/4P3/1Pk2K2/8 b - - 0 69
Error parsing move Kxb2: illegal san: 'Kxb2' in 6R1/8/8/3p4/p2B4/4P3/1Pk2K2/8 b - - 0 69
Error parsing move Kxb2: illegal san: 'Kxb2' in 6R1/8/8/3p4/p2B4/4P3/1Pk2K2/8 b - - 0 69
<__main__.GPTPlayer object at 0x7fa26d51a990> provided illegal moves for 5 attempts.
Game over: 5 consecutive illegal moves from <__main__.GPTPlayer object at 0x7fa26d51a990>

Game over. Total time: 1168.2017614841461 seconds
Result: *
. . . . . . R .
. . . . . . . .
. . . . . . . .
. . . p . . . .
p . . B . . . .
. . . . P . . .
. P k . . K . .
. . . . . . . .

1. d4  Nf6 
2. Bf4  g6 
3. Nf3  Bg7 
4. h3  O-O 
5. c3  d6 
6. Nbd2  Nbd7 
7. Bh2  b6 
8. Qc2  Bb7 
9. e3  c5 
10. Bd3  Rc8 
11. O-O  Rc7 
12. Rfe1  Qa8 
13. Qb1  Rfc8 
14. a4  a6 
15. Qc2  cxd4 
16. exd4  Nd5 
17. Qb3  N7f6 
18. c4  Nb4 
19. Qxb4  Bxf3 
20. Nxf3  Qb7 
21. Bf1  Ne4 
22. Qb3  f5 
23. Qd1  Kh8 
24. Bf4  h6 
25. b3  g5 
26. Bc1  e5 
27. Be3  f4 
28. Bd2  Nxd2 
29. Nxd2  exd4 
30. Bd3  d5 
31. Re6  dxc4 
32. Nxc4  Rc6 
33. Qe1  Rxe6 
34. Qxe6  b5 
35. Nd6  Qc6 
36. Nf7+  Kg8 
37. Nd6+  Kh8 
38. Qf5  Kg8 
39. Kh2  Rc7 
40. Qe6+  Kh8 
41. Nf7+  Kg8 
42. Nxh6+  Kh8 
43. Qg8# 
Game over. Total time: 723.8033375740051 seconds
Result: 1-0
. . . . . . Q k
. . r . . . b .
p . q . . . . N
. p . . . . p .
P . . p . p . .
. P . B . . . P
. . . . . P P K
R . . . . . . .

1. g3  e5 
2. Nf3  Nc6 
3. d4  e4 
4. Ng5  d5 
5. f3  h6 
6. Nh3  Nf6 
7. Nf2  Bf5 
8. Nc3  Bb4 
9. g4  Bg6 
10. Bg2  Qe7 
11. O-O  O-O-O 
12. Bf4  Rhe8 
13. e3  Bxc3 
14. bxc3  Na5 
15. a4  Nc4 
16. a5  exf3 
17. Qxf3  Nd2 
18. Qd1  Nxf1 
19. Kxf1  Ne4 
20. a6  b6 
21. Nxe4  Bxe4 
22. Kg1  Bxg2 
23. Kxg2  Qe4+ 
24. Kh3  f5 
25. Be5  Qxe3+ 
26. Kh4  g5+ 
27. Kh5  Qh3+ 
28. Kg6  Re6+ 
29. Kf7  Rde8 
30. Qe1  R8e7+ 
31. Kg8  Qxg4 
32. Bg7  Rxe1 
33. Rxe1  Rxe1 
34. Be5  Rxe5 
35. Kf8  Re6 
36. h4  gxh4 
37. Kf7  Qg6+ 
38. Kf8  Re8# 
Game over. Total time: 592.5315887928009 seconds
Result: 0-1
. . k . r K . .
p . p . . . . .
P p . . . . q p
. . . p . p . .
. . . P . . . p
. . P . . . . .
. . P . . . . .
. . . . . . . .

1. d4  Nf6 
2. Nf3  e6 
3. g3  d5 
4. c4  dxc4 
5. Nc3  a6 
6. Ne5  c5 
7. dxc5  Qxd1+ 
8. Nxd1  Bxc5 
9. Nxc4  b5 
10. Na5  Bb4+ 
11. Bd2  Bxd2+ 
12. Kxd2  Ra7 
13. Bg2  Rd7+ 
14. Ke1  Ke7 
15. f4  Rhd8 
16. Nf2  Rc7 
17. Bf3  Rc2 
18. g4  Rxb2 
19. g5  Nd5 
20. Bxd5  Rxd5 
21. Nb3  Nc6 
22. Ne4  Nd4 
23. Nxd4  Rxd4 
24. f5  Rxe4 
25. f6+  gxf6 
26. Kf1  fxg5 
27. h3  Rexe2 
28. h4  g4 
29. Rg1  h5 
30. Rc1  Rec2 
31. Rxc2  Rxc2 
32. Rxg4  hxg4 
33. a3  g3 
34. Kg1  Bb7 
35. h5  Rc1# 
Game over. Total time: 557.3561835289001 seconds
Result: 0-1
. . . . . . . .
. b . . k p . .
p . . . p . . .
. p . . . . . P
. . . . . . . .
P . . . . . p .
. . . . . . . .
. . r . . . K .

1. c4  Nf6 
2. Nf3  e6 
3. g3  d5 
4. d4  Be7 
5. Nc3  O-O 
6. b3  c5 
7. Bg2  cxd4 
8. Nxd4  e5 
9. cxd5  exd4 
10. Qxd4  Nc6 
11. Qc4  Ne5 
12. Qd4  Nc6 
13. Qe3  Nb4 
14. Qd2  Bf5 
15. O-O  Rc8 
16. Rd1  Bc5 
17. Ba3  Ng4 
18. Bxb4  Bxb4 
19. Qf4  Bxc3 
20. Qxf5  Bxa1 
21. Qxc8  Qxc8 
22. e3  Qc2 
23. Rxa1  Qxf2+ 
24. Kh1  Nxe3 
25. Be4  Re8 
26. g4  Rxe4 
27. d6  Qg2# 
Game over. Total time: 440.9347496032715 seconds
Result: 0-1
. . . . . . k .
p p . . . p p p
. . . P . . . .
. . . . . . . .
. . . . r . P .
. P . . n . . .
P . . . . . q P
R . . . . . . K

1. d4  Nf6 
2. g3  g6 
3. c4  Bg7 
4. Nc3  O-O 
5. e3  d6 
6. Nge2  e5 
7. b3  exd4 
8. exd4  Re8 
9. h3  c5 
10. dxc5  Ne4 
11. Nxe4  Rxe4 
12. Be3  Bxa1 
13. Qxa1  dxc5 
14. Bh6  f6 
15. Qb2  Nc6 
16. Bg2  Re8 
17. O-O  Be6 
18. g4  Qe7 
19. Ng3  Nd4 
20. Ne4  Rad8 
21. Re1  b6 
22. Re3  Qf7 
23. Bf4  Qg7 
24. Nd6  Re7 
25. b4  f5 
26. Qd2  fxg4 
27. bxc5  bxc5 
28. Be5  Qf8 
29. Rg3  Bf5 
30. Bd5+  Ne6 
31. hxg4  Bb1 
32. Rf3  Bf5 
33. Rxf5  gxf5 
34. Qg5+  Rg7 
35. Bxe6+  Kh8 
36. Bxg7+  Qxg7 
37. Qxd8+ 1-0, player has resigned
<__main__.GPTPlayer object at 0x7fa26d51a990> resigned with result: *

Game over. Total time: 622.9979684352875 seconds
Result: *
. . . Q . . . k
p . . . . . q p
. . . N B . . .
. . p . . p . .
. . P . . . P .
. . . . . . . .
P . . . . P . .
. . . . . . K .

